apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wiredoor-gateway.fullname" . }}
  labels:
    {{- include "wiredoor-gateway.labels" . | nindent 4 }}
spec:
  # {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  # {{- end }}
  selector:
    matchLabels:
      {{- include "wiredoor-gateway.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if or .Values.wiredoor.server .Values.wiredoor.token }}
        checksum/wiredoor-secrets: "{{ toJson .Values.wiredoor | sha256sum }}"
        {{- end }}
        {{- if .Values.podAnnotations }}
        {{ toYaml .Values.podAnnotations | indent 8 }}
        {{- end }}
      labels:
        {{- include "wiredoor-gateway.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "wiredoor-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if or .Values.wiredoor.server .Values.wiredoor.token }}
          envFrom:
            - secretRef:
                name: "wiredoor-secrets"
          {{- end }}
          {{- if and .Values.service .Values.service.port }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
