{{- if or .Values.wiredoor.server .Values.wiredoor.token }}
apiVersion: v1
kind: Secret
metadata:
  name: wiredoor-secrets
data:
  WIREDOOR_URL: {{ .Values.wiredoor.server }}
  TOKEN: {{ .Values.wiredoor.token }}
{{- end }}