{{- if or .Values.wiredoor.server .Values.wiredoor.token }}
apiVersion: v1
kind: Secret
metadata:
  name: wiredoor-secrets
data:
  WIREDOOR_URL: {{ .Values.wiredoor.server | b64enc | quote }}
  TOKEN: {{ .Values.wiredoor.token | b64enc | quote }}
{{- end }}