name: Publish Helm Charts

on:
  push:
    branches:
      - main
    # paths:
    #   - 'charts/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.3

      - name: Configure Git user
        run: |
          git config --global user.email "github-actions@wiredoor.net"
          git config --global user.name "GitHub Actions"

      - name: Package Charts
        run: |
          ls -alh charts
          mkdir -p packaged
          for chart in charts/*; do
            if [ -d "$chart" ]; then
              echo "packaging chart: ${chart}"
              helm package "$chart" -u -d packaged/
            fi
          done
          ls -alh packaged

      - name: Checkout gh-pages branch
        run: |
          git fetch origin gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages

      - name: Download existing index.yaml
        run: |
          if [ -f index.yaml ]; then
            mv index.yaml old_index.yaml
          fi

      - name: Update helm repo
        run: |
          ls -alh ./
          mv packaged/* ./ && rm -rf packaged

          helm repo index --merge old_index.yaml --url "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}" .

          rm old_index.yaml

      # - name: Index Helm Charts
      #   run: |
      #     gh_pages_branch="gh-pages"
      #     repo_url="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"

      #     git fetch origin $gh_pages_branch --depth=1 || true
      #     mkdir -p gh-pages
      #     if git ls-remote --exit-code --heads origin $gh_pages_branch; then
      #       git checkout $gh_pages_branch -- gh-pages/index.yaml || true
      #     fi

      #     helm repo index packaged --url "$repo_url" --merge gh-pages/index.yaml || helm repo index packaged --url "$repo_url"

      #     mv packaged/* gh-pages/

      - name: Add custom index.html
        run: |
          echo '<!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Wiredoor Helm Charts</title>
          </head>
          <body>
              <h1>Wiredoor Charts for Kubernetes</h1>
              <p>You can find available helm charts provided by <a href="https://www.wiredoor.net">Wiredoor</a>, ready to lauch on Kubernetes using <a href="https://github.com/helm/helm">Helm</a>.

              <h2>Usage</h2>

              <code>
                $ helm repo add wiredoor https://charts.wiredoor.net
                $ helm search repo wiredoor
                $ helm install my-wiredoor-release wiredoor/wiredoor-gateway --set wiredoor.server=https://my-wiredoor.clients.wiredoor.net --set wiredoor.token=secret_access_token 
              </code>

              <p>For more information, please refer to the <a href="https://github.com/wiredoor/charts">Wiredoor charts project on github</a></p>
          </body>
          </html>' > index.html

      - name: Deploy to GitHub Pages
        run: |
          git add .
          git commit -m "chore: Update Helm chart repository"
          git push origin gh-pages